using System.Globalization;
using System.Resources;

namespace AudioBookReader.App.Resources.Strings;

/// <summary>
/// Every word the app says, read from the resource files beside this one.
///
/// Written out rather than generated by the designer, so it builds the same from a command line as
/// it does from an IDE and so nothing depends on a tool having been run. Kept in step with the .resx
/// files by the script that writes all three.
///
/// Each property reads the resource at the moment it is asked, against whatever culture is current.
/// That is what lets a language change take effect: the shell is rebuilt, every page asks again,
/// and every answer comes back in the new language.
/// </summary>
public static class Strings
{
    private static readonly ResourceManager Resources =
        new("AudioBookReader.App.Resources.Strings.AppResources", typeof(Strings).Assembly);

    /// <summary>One string by name, for the few callers that choose their key at runtime.</summary>
    public static string Get(string key) => Resources.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    /// <summary>The app's own name, shown wherever it names itself rather than the OS-level
    /// launcher label (which follows the phone's locale independently — see
    /// Platforms/Android/Resources/values{-hr}/strings.xml).</summary>
    public static string App_Name => Get(nameof(App_Name));
    /// <summary>Dismissing a sheet or dialog.</summary>
    public static string Common_Cancel => Get(nameof(Common_Cancel));
    /// <summary>Delete</summary>
    public static string Common_Delete => Get(nameof(Common_Delete));
    /// <summary>Close</summary>
    public static string Common_Close => Get(nameof(Common_Close));
    /// <summary>Yes</summary>
    public static string Common_Yes => Get(nameof(Common_Yes));
    /// <summary>No</summary>
    public static string Common_No => Get(nameof(Common_No));
    /// <summary>The shelf: the first screen.</summary>
    public static string Library_Title => Get(nameof(Library_Title));
    /// <summary>Tab bar label.</summary>
    public static string Library_Tab => Get(nameof(Library_Tab));
    /// <summary>The shelf is empty</summary>
    public static string Library_EmptyTitle => Get(nameof(Library_EmptyTitle));
    /// <summary>Add an audiobook 🎧, an ebook 📖, or both. Add both for the same title and the text starts foll…</summary>
    public static string Library_EmptyBody => Get(nameof(Library_EmptyBody));
    /// <summary>☁ fetches books from your Audiobookshelf server.</summary>
    public static string Library_EmptyServer => Get(nameof(Library_EmptyServer));
    /// <summary>Goes from the player to the text.</summary>
    public static string Player_Read => Get(nameof(Player_Read));
    /// <summary>Aligning text to narration</summary>
    public static string Details_AlignmentSection => Get(nameof(Details_AlignmentSection));
    /// <summary>Measures while you read, rather than up front.</summary>
    public static string Details_LiveAlignment => Get(nameof(Details_LiveAlignment));
    /// <summary>Align the whole book up front</summary>
    public static string Details_AlignAhead => Get(nameof(Details_AlignAhead));
    /// <summary>Stop aligning</summary>
    public static string Details_StopAlignment => Get(nameof(Details_StopAlignment));
    /// <summary>Files</summary>
    public static string Details_FilesSection => Get(nameof(Details_FilesSection));
    /// <summary>Add audiobook</summary>
    public static string Details_AddAudio => Get(nameof(Details_AddAudio));
    /// <summary>Remove audiobook</summary>
    public static string Details_RemoveAudio => Get(nameof(Details_RemoveAudio));
    /// <summary>Add ebook</summary>
    public static string Details_AddEbook => Get(nameof(Details_AddEbook));
    /// <summary>Remove ebook</summary>
    public static string Details_RemoveEbook => Get(nameof(Details_RemoveEbook));
    /// <summary>Find a page, section heading</summary>
    public static string Details_PageFinderSection => Get(nameof(Details_PageFinderSection));
    /// <summary>Explains what a photo of a page does</summary>
    public static string Details_PageFinderBody => Get(nameof(Details_PageFinderBody));
    /// <summary>Locate a page from a photo, button</summary>
    public static string Details_LocatePage => Get(nameof(Details_LocatePage));
    /// <summary>Action sheet title, camera vs. gallery</summary>
    public static string Details_LocatePageChoose => Get(nameof(Details_LocatePageChoose));
    /// <summary>Take a photo, action sheet option</summary>
    public static string Details_LocatePageCamera => Get(nameof(Details_LocatePageCamera));
    /// <summary>Choose an existing photo, action sheet option</summary>
    public static string Details_LocatePageGallery => Get(nameof(Details_LocatePageGallery));
    /// <summary>Shown while the photo is being read and searched</summary>
    public static string Details_LocatePageWorking => Get(nameof(Details_LocatePageWorking));
    /// <summary>No text could be read from the photo</summary>
    public static string Details_LocatePageNoText => Get(nameof(Details_LocatePageNoText));
    /// <summary>The recognized text wasn't found anywhere in the book</summary>
    public static string Details_LocatePageNotFound => Get(nameof(Details_LocatePageNotFound));
    /// <summary>Camera permission was declined</summary>
    public static string Details_LocatePageNoPermission => Get(nameof(Details_LocatePageNoPermission));
    /// <summary>Button that opens the system's settings page for this app</summary>
    public static string Details_OpenAppSettings => Get(nameof(Details_OpenAppSettings));
    /// <summary>An EPUB 3 whose narration is split over several audio files</summary>
    public static string Import_OverlayManyFiles => Get(nameof(Import_OverlayManyFiles));
    /// <summary>Adding another Audiobookshelf server</summary>
    public static string Server_AddServer => Get(nameof(Server_AddServer));
    public static string Server_AddServerShort => Get(nameof(Server_AddServerShort));
    /// <summary>A server being added, before it has a name</summary>
    public static string Server_NewServer => Get(nameof(Server_NewServer));
    public static string Server_Name => Get(nameof(Server_Name));
    public static string Server_NamePlaceholder => Get(nameof(Server_NamePlaceholder));
    /// <summary>A book's server has been removed</summary>
    public static string Server_Gone => Get(nameof(Server_Gone));
    /// <summary>The EP3 button in the library header</summary>
    public static string Library_ImportReadAlong => Get(nameof(Library_ImportReadAlong));
    /// <summary>Picker prompt for an EPUB 3 with narration</summary>
    public static string Picker_ChooseReadAlong => Get(nameof(Picker_ChooseReadAlong));
    /// <summary>An EPUB chosen with the EP3 button that carries no narration</summary>
    public static string Import_NotReadAlong => Get(nameof(Import_NotReadAlong));
    /// <summary>Progress while the audio inside an EPUB 3 is extracted</summary>
    public static string Progress_UnpackingAudio => Get(nameof(Progress_UnpackingAudio));
    /// <summary>Generic failure reading or searching the photo</summary>
    public static string Details_LocatePageError => Get(nameof(Details_LocatePageError));
    /// <summary>Delete book</summary>
    public static string Details_DeleteBook => Get(nameof(Details_DeleteBook));
    /// <summary>Chapters</summary>
    public static string Reader_NoVoice => Get(nameof(Reader_NoVoice));

    public static string Reader_Chapters => Get(nameof(Reader_Chapters));
    public static string Reader_BookPageOf => Get(nameof(Reader_BookPageOf));
    /// <summary>Bookmarks</summary>
    public static string Bookmarks_Title => Get(nameof(Bookmarks_Title));
    /// <summary>No bookmarks yet. Press and hold the ⚑ flag in the player to keep the spot you are on.</summary>
    public static string Bookmarks_Empty => Get(nameof(Bookmarks_Empty));
    /// <summary>Bookmark this spot</summary>
    public static string Bookmarks_Add => Get(nameof(Bookmarks_Add));
    /// <summary>Settings</summary>
    public static string Settings_Title => Get(nameof(Settings_Title));
    /// <summary>Load on the phone</summary>
    public static string Settings_LoadSection => Get(nameof(Settings_LoadSection));
    /// <summary>Aligning listens to only a tenth of the recording, so even the slowest setting finishes a boo…</summary>
    public static string Settings_LoadBody => Get(nameof(Settings_LoadBody));
    /// <summary>When it may work</summary>
    public static string Settings_WhenSection => Get(nameof(Settings_WhenSection));
    /// <summary>Only while charging</summary>
    public static string Settings_OnlyCharging => Get(nameof(Settings_OnlyCharging));
    /// <summary>Only while the screen is off</summary>
    public static string Settings_OnlyScreenOff => Get(nameof(Settings_OnlyScreenOff));
    /// <summary>Aligning only pauses and resumes — it never loses progress. It also slows itself down if the…</summary>
    public static string Settings_AlignmentNote => Get(nameof(Settings_AlignmentNote));
    /// <summary>Where the app opens</summary>
    public static string Settings_StartSection => Get(nameof(Settings_StartSection));
    /// <summary>Open the server shelf on start</summary>
    public static string Settings_OpenServerOnStart => Get(nameof(Settings_OpenServerOnStart));
    /// <summary>Skips the local shelf and goes straight to your server's books when the app opens. The libra…</summary>
    public static string Settings_OpenServerOnStartNote => Get(nameof(Settings_OpenServerOnStartNote));
    /// <summary>Diagnostics</summary>
    public static string Settings_HelpSection => Get(nameof(Settings_HelpSection));

    public static string Settings_HelpBody => Get(nameof(Settings_HelpBody));

    public static string Settings_ReportProblem => Get(nameof(Settings_ReportProblem));

    public static string Settings_SuggestIdea => Get(nameof(Settings_SuggestIdea));

    public static string Settings_VersionLine => Get(nameof(Settings_VersionLine));

    public static string Settings_DiagnosticsSection => Get(nameof(Settings_DiagnosticsSection));
    /// <summary>Detailed log</summary>
    public static string Settings_VerboseLog => Get(nameof(Settings_VerboseLog));
    /// <summary>Turn this on only to diagnose something — it writes several times a second while a book is open.</summary>
    public static string Settings_VerboseNote => Get(nameof(Settings_VerboseNote));
    /// <summary>Language</summary>
    public static string Settings_LanguageSection => Get(nameof(Settings_LanguageSection));
    /// <summary>Follows the device, which is what most people want.</summary>
    public static string Settings_LanguageSystem => Get(nameof(Settings_LanguageSystem));
    /// <summary>The app restarts its screens when the language changes.</summary>
    public static string Settings_LanguageNote => Get(nameof(Settings_LanguageNote));
    /// <summary>The product's own name; not translated.</summary>
    public static string Server_Title => Get(nameof(Server_Title));
    /// <summary>Server address, e.g. 192.168.1.10:13378</summary>
    public static string Server_Address => Get(nameof(Server_Address));
    /// <summary>Sign in with a token instead of a password</summary>
    public static string Server_UseToken => Get(nameof(Server_UseToken));
    /// <summary>Username</summary>
    public static string Server_Username => Get(nameof(Server_Username));
    /// <summary>Password</summary>
    public static string Server_Password => Get(nameof(Server_Password));
    public static string Server_ShowPassword => Get(nameof(Server_ShowPassword));
    public static string Settings_ShareLog => Get(nameof(Settings_ShareLog));
    /// <summary>Remember sign-in</summary>
    public static string Server_RememberSignIn => Get(nameof(Server_RememberSignIn));
    /// <summary>API token from your account page</summary>
    public static string Server_TokenPlaceholder => Get(nameof(Server_TokenPlaceholder));
    /// <summary>Connect</summary>
    public static string Server_Connect => Get(nameof(Server_Connect));
    /// <summary>Everything is kept in the device's protected store, with the key in the system keystore. With…</summary>
    public static string Server_SecurityNote => Get(nameof(Server_SecurityNote));
    /// <summary>Trust this server's certificate, even if self-signed</summary>
    public static string Server_TrustAnyCertificate => Get(nameof(Server_TrustAnyCertificate));
    /// <summary>Skips checking who this server's certificate actually belongs to — only turn this on for a s…</summary>
    public static string Server_TrustAnyCertificateWarning => Get(nameof(Server_TrustAnyCertificateWarning));
    /// <summary>Disconnect</summary>
    public static string Server_Disconnect => Get(nameof(Server_Disconnect));
    /// <summary>On the server</summary>
    public static string ServerBook_OnServer => Get(nameof(ServerBook_OnServer));
    /// <summary>Download</summary>
    public static string ServerBook_Download => Get(nameof(ServerBook_Download));

    public static string ServerBook_DownloadBoth => Get(nameof(ServerBook_DownloadBoth));

    public static string ServerBook_JustAudio => Get(nameof(ServerBook_JustAudio));

    public static string ServerBook_JustEbook => Get(nameof(ServerBook_JustEbook));

    public static string ServerBook_DownloadAudio => Get(nameof(ServerBook_DownloadAudio));

    public static string ServerBook_DownloadEbook => Get(nameof(ServerBook_DownloadEbook));

    public static string ServerBook_AlreadyHere => Get(nameof(ServerBook_AlreadyHere));

    public static string ServerBook_AudioHereTextMissing => Get(nameof(ServerBook_AudioHereTextMissing));

    public static string ServerBook_TextHereAudioMissing => Get(nameof(ServerBook_TextHereAudioMissing));
    /// <summary>Stop downloading</summary>
    public static string ServerBook_CancelDownload => Get(nameof(ServerBook_CancelDownload));
    /// <summary>Open book</summary>
    public static string ServerBook_OpenBook => Get(nameof(ServerBook_OpenBook));
    /// <summary>Loading audiobook…</summary>
    public static string Progress_LoadingAudiobook => Get(nameof(Progress_LoadingAudiobook));
    /// <summary>Reading ebook…</summary>
    public static string Progress_ReadingEbook => Get(nameof(Progress_ReadingEbook));
    /// <summary>Reading chapters…</summary>
    public static string Progress_ReadingChapters => Get(nameof(Progress_ReadingChapters));
    /// <summary>Reading text…</summary>
    public static string Progress_ReadingText => Get(nameof(Progress_ReadingText));
    /// <summary>Starting alignment…</summary>
    public static string Progress_StartingAlignment => Get(nameof(Progress_StartingAlignment));
    /// <summary>Stopped — it will carry on from here</summary>
    public static string Progress_Stopped => Get(nameof(Progress_Stopped));
    /// <summary>{0} is the chapter number.</summary>
    public static string Chapter_Numbered => Get(nameof(Chapter_Numbered));
    /// <summary>Title of the chapter chooser.</summary>
    public static string Chapter_Pick => Get(nameof(Chapter_Pick));
    /// <summary>{0} is a duration like 4:12:30.</summary>
    public static string Duration_Label => Get(nameof(Duration_Label));
    /// <summary>⏱ Stop after</summary>
    public static string Player_SleepAfter => Get(nameof(Player_SleepAfter));
    /// <summary>End of chapter</summary>
    public static string Player_SleepEndOfChapter => Get(nameof(Player_SleepEndOfChapter));
    /// <summary>Off</summary>
    public static string Player_SleepOff => Get(nameof(Player_SleepOff));
    /// <summary>{0} is a whole number of minutes.</summary>
    public static string Player_SleepMinutes => Get(nameof(Player_SleepMinutes));
    /// <summary>Clear what was measured and start clean</summary>
    public static string Align_ClearMeasured => Get(nameof(Align_ClearMeasured));
    /// <summary>Align again from the start</summary>
    public static string Align_AgainFromStart => Get(nameof(Align_AgainFromStart));
    /// <summary>Nothing measured yet.</summary>
    public static string Align_NothingMeasured => Get(nameof(Align_NothingMeasured));
    /// <summary>{0} is a sentence saying how much has been measured.</summary>
    public static string Align_LiveSummary => Get(nameof(Align_LiveSummary));
    /// <summary>The earlier alignment was made by an older, less accurate method and will be worked out again.</summary>
    public static string Align_Stale => Get(nameof(Align_Stale));
    /// <summary>Not aligned yet.</summary>
    public static string Align_NotAligned => Get(nameof(Align_NotAligned));
    /// <summary>{0} is a chapter number.</summary>
    public static string Align_ResumeFrom => Get(nameof(Align_ResumeFrom));
    /// <summary>Delete the book?</summary>
    public static string Dialog_DeleteBookTitle => Get(nameof(Dialog_DeleteBookTitle));
    /// <summary>{0} is the book's title.</summary>
    public static string Dialog_DeleteBookBody => Get(nameof(Dialog_DeleteBookBody));
    /// <summary>{0} is 'the audiobook' or 'the ebook'.</summary>
    public static string Dialog_RemoveTitle => Get(nameof(Dialog_RemoveTitle));
    /// <summary>The rest of the book stays. Bring the same file back later and the alignment is not repeated.</summary>
    public static string Dialog_RemoveBody => Get(nameof(Dialog_RemoveBody));
    /// <summary>Remove</summary>
    public static string Dialog_Remove => Get(nameof(Dialog_Remove));
    /// <summary>Fills the blank in 'Remove …?'.</summary>
    public static string Dialog_TheAudiobook => Get(nameof(Dialog_TheAudiobook));
    /// <summary>Fills the blank in 'Remove …?'.</summary>
    public static string Dialog_TheEbook => Get(nameof(Dialog_TheEbook));
    /// <summary>Clear what was measured?</summary>
    public static string Dialog_ClearMeasuredTitle => Get(nameof(Dialog_ClearMeasuredTitle));
    /// <summary>Align again?</summary>
    public static string Dialog_RealignTitle => Get(nameof(Dialog_RealignTitle));
    /// <summary>Continues with one of the two sentences below.</summary>
    public static string Dialog_RealignBody => Get(nameof(Dialog_RealignBody));
    /// <summary>. Everything from here is measured as you read. The book itself and your place are untouched.</summary>
    public static string Dialog_RealignLiveTail => Get(nameof(Dialog_RealignLiveTail));
    /// <summary> and worked out again. The book itself and your place are untouched.</summary>
    public static string Dialog_RealignAheadTail => Get(nameof(Dialog_RealignAheadTail));
    /// <summary>Align again</summary>
    public static string Dialog_RealignConfirm => Get(nameof(Dialog_RealignConfirm));
    /// <summary>Delete the bookmark?</summary>
    public static string Dialog_DeleteBookmarkTitle => Get(nameof(Dialog_DeleteBookmarkTitle));
    /// <summary>The text will follow the narration once alignment finishes. Start it from ☰.</summary>
    public static string Reader_WillFollow => Get(nameof(Reader_WillFollow));
    /// <summary>Measuring this part — the text starts in a moment.</summary>
    public static string Reader_MeasuringHere => Get(nameof(Reader_MeasuringHere));
    /// <summary>This part of the book is not aligned yet.</summary>
    public static string Reader_PartNotAligned => Get(nameof(Reader_PartNotAligned));
    /// <summary>Chapter {0} is not aligned yet — start aligning on the book's page.</summary>
    public static string Reader_ChapterNotAligned => Get(nameof(Reader_ChapterNotAligned));
    /// <summary>This part is not measured yet. You can play the audio, but the text will not follow it for now.</summary>
    public static string Reader_UnmeasuredCanPlay => Get(nameof(Reader_UnmeasuredCanPlay));
    /// <summary>{0} is a short error code.</summary>
    public static string Reader_AudioFailed => Get(nameof(Reader_AudioFailed));
    /// <summary>Preparing the chapter…</summary>
    public static string Reader_PreparingChapter => Get(nameof(Reader_PreparingChapter));
    /// <summary>A reader colour scheme.</summary>
    public static string Reader_ThemeDim => Get(nameof(Reader_ThemeDim));
    /// <summary>A reader colour scheme.</summary>
    public static string Reader_ThemeNight => Get(nameof(Reader_ThemeNight));
    /// <summary>A reader colour scheme.</summary>
    public static string Reader_ThemePaper => Get(nameof(Reader_ThemePaper));
    /// <summary>A reader colour scheme.</summary>
    public static string Reader_ThemeSepia => Get(nameof(Reader_ThemeSepia));
    /// <summary>A reader colour scheme.</summary>
    public static string Reader_ThemeLight => Get(nameof(Reader_ThemeLight));
    /// <summary>Align on the go has stopped — close and reopen the reader to try again.</summary>
    public static string Live_Stopped => Get(nameof(Live_Stopped));
    /// <summary>The speech model has not been downloaded yet.</summary>
    public static string Live_NoModel => Get(nameof(Live_NoModel));
    /// <summary>The speech model has not been downloaded yet — start aligning from the book's page.</summary>
    public static string Live_NoModelHint => Get(nameof(Live_NoModelHint));
    public static string Model_DownloadFailed => Get(nameof(Model_DownloadFailed));
    public static string Model_Ready => Get(nameof(Model_Ready));
    /// <summary>{0} is a whole number of seconds.</summary>
    public static string Live_MeasuredAhead => Get(nameof(Live_MeasuredAhead));
    /// <summary>Aligning on the go…</summary>
    public static string Live_Working => Get(nameof(Live_Working));
    /// <summary>The limit of {0} bookmarks is reached. Delete one before adding another.</summary>
    public static string Bookmarks_LimitReached => Get(nameof(Bookmarks_LimitReached));
    /// <summary>Nothing to save — play the book or open it in the reader.</summary>
    public static string Bookmarks_NoPosition => Get(nameof(Bookmarks_NoPosition));
    /// <summary>This does not look like an audio file — no sound was found in it.</summary>
    public static string Import_NotAudio => Get(nameof(Import_NotAudio));
    /// <summary>“{0}” cannot be read as an audiobook — neither its tags nor its sound.</summary>
    public static string Import_Unreadable => Get(nameof(Import_Unreadable));
    /// <summary>Type the server address.</summary>
    public static string Server_EnterAddress => Get(nameof(Server_EnterAddress));
    /// <summary>Paste the token from your account page on the server.</summary>
    public static string Server_PasteToken => Get(nameof(Server_PasteToken));
    /// <summary>Connecting…</summary>
    public static string Server_Connecting => Get(nameof(Server_Connecting));
    /// <summary>Disconnected.</summary>
    public static string Server_Disconnected => Get(nameof(Server_Disconnected));
    /// <summary>Reading libraries…</summary>
    public static string Server_ReadingLibraries => Get(nameof(Server_ReadingLibraries));
    /// <summary>Reading books…</summary>
    public static string Server_ReadingBooks => Get(nameof(Server_ReadingBooks));
    /// <summary>Reading books… {0}</summary>
    public static string Server_ReadingBooksCount => Get(nameof(Server_ReadingBooksCount));
    /// <summary>Reading details…</summary>
    public static string Server_ReadingDetails => Get(nameof(Server_ReadingDetails));
    /// <summary>This server has no library of books.</summary>
    public static string Server_NoBookLibraries => Get(nameof(Server_NoBookLibraries));
    /// <summary>The library “{0}” is empty.</summary>
    public static string Server_LibraryEmpty => Get(nameof(Server_LibraryEmpty));
    /// <summary>{0} books in “{1}”.</summary>
    public static string Server_BooksInLibrary => Get(nameof(Server_BooksInLibrary));
    /// <summary>{0} files — cannot be assembled into one book yet</summary>
    public static string Server_SplitFiles => Get(nameof(Server_SplitFiles));
    /// <summary>The server keeps the audio split across {0} files. A book here can still hold only one, so th…</summary>
    public static string Server_SplitFilesLong => Get(nameof(Server_SplitFilesLong));
    /// <summary>This item on the server has neither audio nor text.</summary>
    public static string Server_NothingToDownload => Get(nameof(Server_NothingToDownload));
    /// <summary>Audiobook and ebook — the text can follow the narration.</summary>
    public static string Server_HasBoth => Get(nameof(Server_HasBoth));
    /// <summary>Audiobook only.</summary>
    public static string Server_AudioOnly => Get(nameof(Server_AudioOnly));
    /// <summary>Ebook only.</summary>
    public static string Server_EbookOnly => Get(nameof(Server_EbookOnly));
    /// <summary>Downloading audio — {0}</summary>
    public static string Server_DownloadingAudio => Get(nameof(Server_DownloadingAudio));
    /// <summary>Downloading text — {0}</summary>
    public static string Server_DownloadingText => Get(nameof(Server_DownloadingText));
    /// <summary>The book is in Books.</summary>
    public static string Server_InLibraryNow => Get(nameof(Server_InLibraryNow));
    /// <summary>The download was stopped.</summary>
    public static string Server_DownloadCancelled => Get(nameof(Server_DownloadCancelled));
    /// <summary>Where should the book go?</summary>
    public static string Server_WhereToSave => Get(nameof(Server_WhereToSave));
    /// <summary>{0} is the folder's name.</summary>
    public static string Server_FolderNamed => Get(nameof(Server_FolderNamed));
    /// <summary>The Audiobooks folder</summary>
    public static string Server_FolderAudiobooks => Get(nameof(Server_FolderAudiobooks));
    /// <summary>The app's own storage</summary>
    public static string Server_AppStorage => Get(nameof(Server_AppStorage));
    /// <summary>Little cores, a quarter of the time. You will barely notice the phone working.</summary>
    public static string Budget_ThriftyDetail => Get(nameof(Budget_ThriftyDetail));
    /// <summary>Little cores, half the time. Works in the background while you use the phone normally.</summary>
    public static string Budget_BalancedDetail => Get(nameof(Budget_BalancedDetail));
    /// <summary>All cores, no pauses. Best with “only while charging” and the screen off.</summary>
    public static string Budget_FastDetail => Get(nameof(Budget_FastDetail));
    /// <summary>No battery limit</summary>
    public static string Settings_NoBatteryLimit => Get(nameof(Settings_NoBatteryLimit));
    /// <summary>{0} is a whole number, e.g. 20.</summary>
    public static string Settings_PauseBelow => Get(nameof(Settings_PauseBelow));
    /// <summary>The gentlest of three settings for how hard alignment may work the phone.</summary>
    public static string Budget_Thrifty => Get(nameof(Budget_Thrifty));
    /// <summary>The middle of three settings for how hard alignment may work the phone.</summary>
    public static string Budget_Balanced => Get(nameof(Budget_Balanced));
    /// <summary>The hardest of three settings for how hard alignment may work the phone.</summary>
    public static string Budget_Fast => Get(nameof(Budget_Fast));
    /// <summary>synced</summary>
    public static string Sync_Complete => Get(nameof(Sync_Complete));
    /// <summary>partly synced</summary>
    public static string Sync_Partial => Get(nameof(Sync_Partial));
    /// <summary>aligning</summary>
    public static string Sync_InProgress => Get(nameof(Sync_InProgress));
    /// <summary>waiting to be aligned</summary>
    public static string Sync_Pending => Get(nameof(Sync_Pending));
    /// <summary>aligning failed</summary>
    public static string Sync_Failed => Get(nameof(Sync_Failed));
    /// <summary>Waiting for a charger</summary>
    public static string Gate_WaitingForCharger => Get(nameof(Gate_WaitingForCharger));
    /// <summary>Waiting for the screen to go off</summary>
    public static string Gate_WaitingForScreenOff => Get(nameof(Gate_WaitingForScreenOff));
    /// <summary>The download folder cannot be read.</summary>
    public static string Folder_Unreadable => Get(nameof(Folder_Unreadable));
    /// <summary>The download folder no longer exists.</summary>
    public static string Folder_Gone => Get(nameof(Folder_Gone));
    /// <summary>The book could not be opened.</summary>
    public static string Reader_CouldNotOpen => Get(nameof(Reader_CouldNotOpen));
    /// <summary>Aligning finished</summary>
    public static string Progress_Finished => Get(nameof(Progress_Finished));
    /// <summary>Fetching the speech model…</summary>
    public static string Progress_DownloadingModel => Get(nameof(Progress_DownloadingModel));
    /// <summary>{0} is a whole number.</summary>
    public static string Progress_DownloadingModelPercent => Get(nameof(Progress_DownloadingModelPercent));
    /// <summary>{0} and {1} are chapter numbers, {2} is a percentage such as 40%.</summary>
    public static string Progress_ChapterOf => Get(nameof(Progress_ChapterOf));
    /// <summary>{0} is a percentage. Used when the book has no chapter marks, so there is only one.</summary>
    public static string Progress_WholeBook => Get(nameof(Progress_WholeBook));
    /// <summary>Appended to the line above. Keep the leading separator.</summary>
    public static string Progress_ThermalSlowed => Get(nameof(Progress_ThermalSlowed));
    /// <summary>Name of the Android notification channel.</summary>
    public static string Notification_AlignChannel => Get(nameof(Notification_AlignChannel));
    /// <summary>Progress of pairing an audiobook with its text</summary>
    public static string Notification_AlignChannelBody => Get(nameof(Notification_AlignChannelBody));
    /// <summary>{0} is a whole number.</summary>
    public static string Notification_WholeBook => Get(nameof(Notification_WholeBook));
    /// <summary>{0} is a whole number.</summary>
    public static string Gate_BatteryBelow => Get(nameof(Gate_BatteryBelow));
    /// <summary>Alignment is impossible on this device (32-bit system, no speech recognition).</summary>
    public static string Details_AlignmentUnsupported => Get(nameof(Details_AlignmentUnsupported));
    /// <summary>Preparing to stream.</summary>
    public static string Server_PreparingStream => Get(nameof(Server_PreparingStream));
    /// <summary>Button: add the book to play from the server.</summary>
    public static string ServerBook_Stream => Get(nameof(ServerBook_Stream));
    /// <summary>After adding a streamed book.</summary>
    public static string ServerBook_StreamReady => Get(nameof(ServerBook_StreamReady));
    /// <summary>Alignment unavailable for a streamed book.</summary>
    public static string Details_StreamedNoAlign => Get(nameof(Details_StreamedNoAlign));
    /// <summary>A streamed book, seen from the server page.</summary>
    public static string ServerBook_StreamedHere => Get(nameof(ServerBook_StreamedHere));
    /// <summary>Shelf row: the audio is played from the server.</summary>
    public static string Library_Streamed => Get(nameof(Library_Streamed));
    /// <summary>Progress on the server is newer than here.</summary>
    public static string Sync_ElsewhereTitle => Get(nameof(Sync_ElsewhereTitle));
    /// <summary>{0} there, {1} here, as times.</summary>
    public static string Sync_ElsewhereAudio => Get(nameof(Sync_ElsewhereAudio));
    /// <summary>{0} there, {1} here, as percentages.</summary>
    public static string Sync_ElsewhereText => Get(nameof(Sync_ElsewhereText));
    /// <summary>Jump to the other device's place.</summary>
    public static string Sync_ElsewhereGo => Get(nameof(Sync_ElsewhereGo));
    /// <summary>Keep this device's place.</summary>
    public static string Sync_ElsewhereStay => Get(nameof(Sync_ElsewhereStay));
    /// <summary>Book page: send this alignment over the local network.</summary>
    public static string Share_Button => Get(nameof(Share_Button));
    /// <summary>While discovering.</summary>
    public static string Share_Looking => Get(nameof(Share_Looking));
    /// <summary>Choose a device.</summary>
    public static string Share_ChooseTitle => Get(nameof(Share_ChooseTitle));
    /// <summary>Option: enter an IP address by hand.</summary>
    public static string Share_TypeAddress => Get(nameof(Share_TypeAddress));
    /// <summary>Prompt title.</summary>
    public static string Share_AddressTitle => Get(nameof(Share_AddressTitle));
    /// <summary>Prompt body.</summary>
    public static string Share_AddressBody => Get(nameof(Share_AddressBody));
    /// <summary>Prompt accept.</summary>
    public static string Share_Send => Get(nameof(Share_Send));
    /// <summary>{0} device name.</summary>
    public static string Share_Sending => Get(nameof(Share_Sending));
    /// <summary>{0} device name.</summary>
    public static string Share_Done => Get(nameof(Share_Done));
    /// <summary>{0} device name.</summary>
    public static string Share_NoSuchBook => Get(nameof(Share_NoSuchBook));
    /// <summary>{0} device name.</summary>
    public static string Share_Declined => Get(nameof(Share_Declined));
    /// <summary>Send failed.</summary>
    public static string Share_Unreachable => Get(nameof(Share_Unreachable));
    /// <summary>Receiver prompt title.</summary>
    public static string Share_ReceiveTitle => Get(nameof(Share_ReceiveTitle));
    /// <summary>{0} sender, {1} book title.</summary>
    public static string Share_ReceiveBody => Get(nameof(Share_ReceiveBody));
    /// <summary>Receiver accept.</summary>
    public static string Share_Accept => Get(nameof(Share_Accept));
    /// <summary>Receiver decline.</summary>
    public static string Share_Decline => Get(nameof(Share_Decline));
    /// <summary>Nothing to send.</summary>
    public static string Share_NothingToSend => Get(nameof(Share_NothingToSend));
    /// <summary>{0} IP address(es).</summary>
    public static string Settings_ShareAddress => Get(nameof(Settings_ShareAddress));
    /// <summary>No local address.</summary>
    public static string Settings_ShareNoAddress => Get(nameof(Settings_ShareNoAddress));
    /// <summary>This device has no file picker (televisions usually do not).</summary>
    public static string Picker_Unavailable => Get(nameof(Picker_Unavailable));
    /// <summary>No access to the system's files.</summary>
    public static string Folder_NoSystemAccess => Get(nameof(Folder_NoSystemAccess));
    /// <summary>Not chosen</summary>
    public static string Folder_NotChosen => Get(nameof(Folder_NotChosen));
    /// <summary>Internal storage</summary>
    public static string Folder_InternalStorage => Get(nameof(Folder_InternalStorage));
    /// <summary>No download folder has been chosen.</summary>
    public static string Folder_NotChosenError => Get(nameof(Folder_NotChosenError));
    /// <summary>{0} is a file name.</summary>
    public static string Folder_CannotCreateFile => Get(nameof(Folder_CannotCreateFile));
    /// <summary>{0} is a file name.</summary>
    public static string Folder_CannotWrite => Get(nameof(Folder_CannotWrite));
    /// <summary>{0} is a folder name.</summary>
    public static string Folder_CannotCreateFolder => Get(nameof(Folder_CannotCreateFolder));
    /// <summary>{0} is a file name or location.</summary>
    public static string Import_CannotOpen => Get(nameof(Import_CannotOpen));
    /// <summary>Choose an audiobook</summary>
    public static string Picker_ChooseAudiobook => Get(nameof(Picker_ChooseAudiobook));
    /// <summary>Choose an ebook</summary>
    public static string Picker_ChooseEbook => Get(nameof(Picker_ChooseEbook));
    /// <summary>Add an audiobook</summary>
    public static string Picker_AddAudiobook => Get(nameof(Picker_AddAudiobook));
    /// <summary>Add an ebook</summary>
    public static string Picker_AddEbook => Get(nameof(Picker_AddEbook));
    /// <summary>Getting ready to align…</summary>
    public static string Progress_PreparingAlignment => Get(nameof(Progress_PreparingAlignment));
    /// <summary>I got no text at all out of this file.</summary>
    public static string Import_NoText => Get(nameof(Import_NoText));
    /// <summary>{0} is a whole number.</summary>
    public static string Progress_CopyingPercent => Get(nameof(Progress_CopyingPercent));
    /// <summary>{0} is a whole number.</summary>
    public static string Progress_CopyingMb => Get(nameof(Progress_CopyingMb));
    /// <summary>{0} is the reason.</summary>
    public static string Error_ImportFailed => Get(nameof(Error_ImportFailed));
    /// <summary>{0} is the reason.</summary>
    public static string Error_DeleteFailed => Get(nameof(Error_DeleteFailed));
    /// <summary>{0} is the reason.</summary>
    public static string Error_AddFailed => Get(nameof(Error_AddFailed));
    /// <summary>{0} and {1} are durations, e.g. “1 h 20 min”.</summary>
    public static string Align_MeasuredOf => Get(nameof(Align_MeasuredOf));
    /// <summary>Fully aligned ({0} chapters).</summary>
    public static string Align_FullyAligned => Get(nameof(Align_FullyAligned));
    /// <summary>Keep the trailing space: another sentence follows.</summary>
    public static string Align_AlignedOf => Get(nameof(Align_AlignedOf));
    /// <summary>Carry on aligning</summary>
    public static string Align_Continue => Get(nameof(Align_Continue));
    /// <summary>Start aligning</summary>
    public static string Align_Start => Get(nameof(Align_Start));
    /// <summary>{1} is an arrow showing whether the list is open.</summary>
    public static string Chapter_Toggle => Get(nameof(Chapter_Toggle));
    /// <summary>Heading of the sleep timer chooser.</summary>
    public static string Player_SleepAfterTitle => Get(nameof(Player_SleepAfterTitle));
    /// <summary>This book has reached its limit of {0} bookmarks.</summary>
    public static string Bookmarks_LimitReachedBook => Get(nameof(Bookmarks_LimitReachedBook));
    /// <summary>{0} is a position, e.g. 1:23:45.</summary>
    public static string Bookmarks_SavedAt => Get(nameof(Bookmarks_SavedAt));
    /// <summary>Saved</summary>
    public static string Bookmarks_Saved => Get(nameof(Bookmarks_Saved));
    /// <summary>Where a bookmark sits in a book with no audio.</summary>
    public static string Bookmarks_AtChar => Get(nameof(Bookmarks_AtChar));
    /// <summary>Text only</summary>
    public static string Media_TextOnly => Get(nameof(Media_TextOnly));
    /// <summary>{0} h {1} min</summary>
    public static string Duration_HoursMinutes => Get(nameof(Duration_HoursMinutes));
    /// <summary>{0} min</summary>
    public static string Duration_Minutes => Get(nameof(Duration_Minutes));
    /// <summary>Following ✓</summary>
    public static string Reader_FollowOn => Get(nameof(Reader_FollowOn));
    /// <summary>Follow</summary>
    public static string Reader_Follow => Get(nameof(Reader_Follow));
    /// <summary>Page appearance</summary>
    public static string Reader_Appearance => Get(nameof(Reader_Appearance));
    /// <summary>Page number within the chapter.</summary>
    public static string Reader_PageOf => Get(nameof(Reader_PageOf));
    /// <summary>Stopping the download…</summary>
    public static string Server_Cancelling => Get(nameof(Server_Cancelling));
    /// <summary>1 book</summary>
    public static string Server_OneBook => Get(nameof(Server_OneBook));
    /// <summary>{0} books</summary>
    public static string Server_BookCount => Get(nameof(Server_BookCount));
    /// <summary>Recently added</summary>
    public static string Server_RecentlyAdded => Get(nameof(Server_RecentlyAdded));
    /// <summary>Not in a series</summary>
    public static string Server_NoSeries => Get(nameof(Server_NoSeries));
    /// <summary>{0} chapters</summary>
    public static string Chapter_Count => Get(nameof(Chapter_Count));
    /// <summary>Button that ends a job that is running.</summary>
    public static string Common_Stop => Get(nameof(Common_Stop));
    /// <summary>Getting ready…</summary>
    public static string Download_Preparing => Get(nameof(Download_Preparing));
    /// <summary>Name of the Android notification channel for books coming from a server.</summary>
    public static string Notification_DownloadChannel => Get(nameof(Notification_DownloadChannel));
    /// <summary>Progress of books being fetched from a server</summary>
    public static string Notification_DownloadChannelBody => Get(nameof(Notification_DownloadChannelBody));
    /// <summary>Another book is being downloaded. Wait for it to finish.</summary>
    public static string Download_AlreadyRunning => Get(nameof(Download_AlreadyRunning));
    /// <summary>Audiobooks folder</summary>
    public static string Destination_FolderTitle => Get(nameof(Destination_FolderTitle));
    /// <summary>Beside the audiobooks already on the phone. Other apps and a computer over a cable can see it…</summary>
    public static string Destination_FolderBody => Get(nameof(Destination_FolderBody));
    /// <summary>{0} is the folder the user picked earlier.</summary>
    public static string Destination_FolderChosen => Get(nameof(Destination_FolderChosen));
    /// <summary>The system will ask you to confirm the folder.</summary>
    public static string Destination_FolderWillAsk => Get(nameof(Destination_FolderWillAsk));
    /// <summary>Internal app storage</summary>
    public static string Destination_AppTitle => Get(nameof(Destination_AppTitle));
    /// <summary>The app’s own space. Nothing else on the phone can see it, and it is deleted along with the app.</summary>
    public static string Destination_AppBody => Get(nameof(Destination_AppBody));
    /// <summary>Books are filed under the author’s name, then the book’s.</summary>
    public static string Destination_Layout => Get(nameof(Destination_Layout));
    /// <summary>How alignment works</summary>
    public static string Help_Title => Get(nameof(Help_Title));
    /// <summary>What it does</summary>
    public static string Help_WhatSection => Get(nameof(Help_WhatSection));
    /// <summary>Pairing an audiobook with its text means finding, for every sentence, the moment it is spoken…</summary>
    public static string Help_WhatBody => Get(nameof(Help_WhatBody));
    /// <summary>Two ways to get there</summary>
    public static string Help_WaysSection => Get(nameof(Help_WaysSection));
    /// <summary>While you read</summary>
    public static string Help_LiveTitle => Get(nameof(Help_LiveTitle));
    /// <summary>Measures the passage you are on, from where the narration is, while the reader is open. Nothi…</summary>
    public static string Help_LiveBody => Get(nameof(Help_LiveBody));
    /// <summary>Ahead of you</summary>
    public static string Help_AheadTitle => Get(nameof(Help_AheadTitle));
    /// <summary>Works through the whole book in the background so it is ready before you get there. This is t…</summary>
    public static string Help_AheadBody => Get(nameof(Help_AheadBody));
    /// <summary>The three settings</summary>
    public static string Help_PresetsSection => Get(nameof(Help_PresetsSection));
    /// <summary>Two threads on the efficiency cores, a quarter of the time. You will barely notice it — and i…</summary>
    public static string Help_PresetThrifty => Get(nameof(Help_PresetThrifty));
    /// <summary>Four threads on the efficiency cores, half the time. The phone stays smooth for everything el…</summary>
    public static string Help_PresetBalanced => Get(nameof(Help_PresetBalanced));
    /// <summary>Every core, no pauses. Several times faster than the other two, and the phone will get warm.</summary>
    public static string Help_PresetFast => Get(nameof(Help_PresetFast));
    /// <summary>Switching presets only takes effect after you stop and restart alignment — it does not change a run…</summary>
    public static string Help_PresetChangeNote => Get(nameof(Help_PresetChangeNote));
    /// <summary>Activate Premium Pro Plus?</summary>
    public static string Premium_ConfirmTitle => Get(nameof(Premium_ConfirmTitle));
    /// <summary>Exclusive perks await.</summary>
    public static string Premium_ConfirmBody => Get(nameof(Premium_ConfirmBody));
    /// <summary>You already have Premium Pro Plus!</summary>
    public static string Premium_Title => Get(nameof(Premium_Title));
    /// <summary>Because everything in this app is free. Always was, always will be.</summary>
    public static string Premium_Body => Get(nameof(Premium_Body));
    /// <summary>Jagshemash! Great success!</summary>
    public static string Premium_Tagline => Get(nameof(Premium_Tagline));
    /// <summary>Why it can be slower than the estimate</summary>
    public static string Help_SlowerSection => Get(nameof(Help_SlowerSection));
    /// <summary>Heat. The moment the system reports the phone warming, the app eases off on its own — first t…</summary>
    public static string Help_SlowerHeat => Get(nameof(Help_SlowerHeat));
    /// <summary>A sleeping phone. Work carries on with the screen off — the app holds the processor awake for…</summary>
    public static string Help_SlowerCores => Get(nameof(Help_SlowerCores));
    /// <summary>What actually finishes a book</summary>
    public static string Help_DoneSection => Get(nameof(Help_DoneSection));
    /// <summary>Fast, with “only while charging” and “only while the screen is off”, overnight. That is what…</summary>
    public static string Help_DoneCharging => Get(nameof(Help_DoneCharging));
    /// <summary>Or do not wait at all: open the reader and read along with the narration. Alignment while rea…</summary>
    public static string Help_DoneReading => Get(nameof(Help_DoneReading));
    /// <summary>When it stops on its own</summary>
    public static string Help_PausedSection => Get(nameof(Help_PausedSection));
    /// <summary>The notification always says why: waiting for a charger, waiting for the screen to go off, or…</summary>
    public static string Help_PausedBody => Get(nameof(Help_PausedBody));
    /// <summary>Delete</summary>
    public static string Delete_Title => Get(nameof(Delete_Title));
    /// <summary>Delete the file too</summary>
    public static string Delete_AlsoFile => Get(nameof(Delete_AlsoFile));
    /// <summary>Removes it from the phone, not just from this library. There is no way back.</summary>
    public static string Delete_AlsoFileNote => Get(nameof(Delete_AlsoFileNote));
    /// <summary>The book is gone from the library. Its file is still on the phone.</summary>
    public static string Delete_FileKept => Get(nameof(Delete_FileKept));
    /// <summary>The book is gone from the library, but the file could not be deleted — permission may have la…</summary>
    public static string Delete_FileRefused => Get(nameof(Delete_FileRefused));
    /// <summary>Remove the audiobook?</summary>
    public static string Delete_RemoveAudioTitle => Get(nameof(Delete_RemoveAudioTitle));
    /// <summary>Remove the ebook?</summary>
    public static string Delete_RemoveEbookTitle => Get(nameof(Delete_RemoveEbookTitle));
    /// <summary>Delete the alignment</summary>
    public static string Align_Clear => Get(nameof(Align_Clear));
    /// <summary>Delete the alignment?</summary>
    public static string Dialog_ClearTitle => Get(nameof(Dialog_ClearTitle));
    /// <summary>Everything measured so far ({0} of {1} chapters) goes. The book and your place in it stay, an…</summary>
    public static string Dialog_ClearBody => Get(nameof(Dialog_ClearBody));
    /// <summary>Title of the app chooser for translating a word.</summary>
    public static string Reader_TranslateChooser => Get(nameof(Reader_TranslateChooser));
    /// <summary>iOS: look the selection up in the system dictionary</summary>
    public static string Reader_TranslateDictionary => Get(nameof(Reader_TranslateDictionary));
    /// <summary>iOS: open Google Translate with the selection</summary>
    public static string Reader_TranslateOnline => Get(nameof(Reader_TranslateOnline));
    /// <summary>iOS: the share sheet, for any installed app that takes text</summary>
    public static string Reader_TranslateShare => Get(nameof(Reader_TranslateShare));

    public static string Reader_TranslateAction => Get(nameof(Reader_TranslateAction));

    public static string Reader_BookmarkAction => Get(nameof(Reader_BookmarkAction));
    /// <summary>Measures the passage you are reading, while you read it. Nothing to wait for.</summary>
    public static string Details_LiveAlignmentNote => Get(nameof(Details_LiveAlignmentNote));
    /// <summary>Works through the whole book in the background, so it is ready before you get there.</summary>
    public static string Details_AlignAheadNote => Get(nameof(Details_AlignAheadNote));
    /// <summary>Recognition accuracy</summary>
    public static string Settings_RecognitionSection => Get(nameof(Settings_RecognitionSection));
    /// <summary>Which speech model listens to the book. A better one mishears less, so fewer stretches are th…</summary>
    public static string Settings_RecognitionBody => Get(nameof(Settings_RecognitionBody));
    /// <summary>Standard</summary>
    public static string Recognition_Tiny => Get(nameof(Recognition_Tiny));
    /// <summary>The small model, about 31 MB. What the app has used until now.</summary>
    public static string Recognition_TinyDetail => Get(nameof(Recognition_TinyDetail));
    /// <summary>More accurate</summary>
    public static string Recognition_Base => Get(nameof(Recognition_Base));
    /// <summary>The next size up, about 58 MB. Around three times longer to align, and noticeably better at l…</summary>
    public static string Recognition_BaseDetail => Get(nameof(Recognition_BaseDetail));

    public static string Settings_SpacingSection => Get(nameof(Settings_SpacingSection));

    public static string Settings_SpacingBody => Get(nameof(Settings_SpacingBody));

    public static string Spacing_60 => Get(nameof(Spacing_60));

    public static string Spacing_60Detail => Get(nameof(Spacing_60Detail));

    public static string Spacing_45 => Get(nameof(Spacing_45));

    public static string Spacing_45Detail => Get(nameof(Spacing_45Detail));

    public static string Spacing_30 => Get(nameof(Spacing_30));

    public static string Spacing_30Detail => Get(nameof(Spacing_30Detail));

    public static string Spacing_15 => Get(nameof(Spacing_15));

    public static string Spacing_15Detail => Get(nameof(Spacing_15Detail));
    /// <summary>Time every word</summary>
    public static string Settings_WordTimes => Get(nameof(Settings_WordTimes));
    /// <summary>Asks the model when each word was spoken instead of assuming an even pace across a few second…</summary>
    public static string Settings_WordTimesNote => Get(nameof(Settings_WordTimesNote));
    /// <summary>Used as a folder name when a book has no author.</summary>
    public static string Server_UnknownAuthor => Get(nameof(Server_UnknownAuthor));
}
